#!/bin/bash
#Rush Weigelt
#4/24/18

gcc -osign sign.c
./sign < /usr/share/dict/words | sort | awk -f squash.awk > out
./sign < /usr/share/dict/words | sort | ./squash > out
awk '{print NF " " $0}' < out | sort -n | tail

